export const carousel_movie_data = [
	{
		adult: false,
		backdrop_path: "/13QFKJa7ZPY3VN0L6sxKuNoLHFf.jpg",
		genre_ids: [28, 80, 18],
		id: 781732,
		original_language: "hi",
		original_title: "Animal",
		overview: "",
		popularity: 61.435,
		poster_path: "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg",
		release_date: "2023-12-01",
		title: "Animal",
		video: false,
		vote_average: 6.747,
		vote_count: 73,
	},
	{
		adult: false,
		backdrop_path: "/u3lWiLi0e0W3aU822QdcxQIGBES.jpg",
		genre_ids: [28, 12],
		id: 962074,
		original_language: "ta",
		original_title: "கேப்டன் மில்லர்",
		overview: "",
		popularity: 50.472,
		poster_path: "/blpuCOI2Qz5pmA2yTMJiQ9tEmFb.jpg",
		release_date: "2024-01-11",
		title: "कैप्टन मिलर",
		video: false,
		vote_average: 7.4,
		vote_count: 13,
	},
	{
		adult: false,
		backdrop_path: "/hObu7eQdEzqh8sxv6QUmI7ZZepU.jpg",
		genre_ids: [28, 12, 53],
		id: 784651,
		original_language: "hi",
		original_title: "फाइटर",
		overview: "",
		popularity: 15.742,
		poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
		release_date: "2024-01-24",
		title: "फाइटर",
		video: false,
		vote_average: 5.923,
		vote_count: 13,
	},
	{
		adult: false,
		backdrop_path: "/zTCZD3GTWszmuQnmMMTib8f0RG9.jpg",
		genre_ids: [28, 80],
		id: 1089737,
		original_language: "te",
		original_title: "సైంధ\u200cవ్",
		overview: "",
		popularity: 11.263,
		poster_path: "/u4PISjJhQGThTOulxr66moCBo9T.jpg",
		release_date: "2024-01-13",
		title: "सैंधव",
		video: false,
		vote_average: 5.7,
		vote_count: 5,
	},
];
export const movies_data = [
	{
		adult: false,
		backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
		genre_ids: [16, 28, 14, 53],
		id: 1311031,
		original_language: "ja",
		original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
		overview:
			"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
		popularity: 850.6515,
		poster_path: "/sUsVimPdA1l162FvdBIlmKBlWHx.jpg",
		release_date: "2025-07-18",
		title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
		video: false,
		vote_average: 7.632,
		vote_count: 243,
	},
	{
		adult: false,
		backdrop_path: "/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg",
		genre_ids: [27, 9648],
		id: 1078605,
		original_language: "en",
		original_title: "Weapons",
		overview:
			"When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
		popularity: 400.3399,
		poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
		release_date: "2025-08-04",
		title: "Weapons",
		video: false,
		vote_average: 7.397,
		vote_count: 1369,
	},
	{
		adult: false,
		backdrop_path: "/fq8gLtrz1ByW3KQ2IM3RMZEIjsQ.jpg",
		genre_ids: [27],
		id: 1038392,
		original_language: "en",
		original_title: "The Conjuring: Last Rites",
		overview:
			"Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.",
		popularity: 375.5061,
		poster_path: "/29ES27icY5CzTcMhlz1H4SdQRod.jpg",
		release_date: "2025-09-03",
		title: "The Conjuring: Last Rites",
		video: false,
		vote_average: 6.629,
		vote_count: 337,
	},
	{
		adult: false,
		backdrop_path: "/mEW9XMgYDO6U0MJcIRqRuSwjzN5.jpg",
		genre_ids: [28, 53],
		id: 1007734,
		original_language: "en",
		original_title: "Nobody 2",
		overview:
			"Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.",
		popularity: 312.21,
		poster_path: "/svXVRoRSu6zzFtCzkRsjZS7Lqpd.jpg",
		release_date: "2025-08-13",
		title: "Nobody 2",
		video: false,
		vote_average: 7.28,
		vote_count: 540,
	},
	{
		adult: false,
		backdrop_path: "/kzeBfhXMRWiykBsqoL3UbfaM0S.jpg",
		genre_ids: [35, 28, 80],
		id: 1035259,
		original_language: "en",
		original_title: "The Naked Gun",
		overview:
			"Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
		popularity: 206.6359,
		poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
		release_date: "2025-07-30",
		title: "The Naked Gun",
		video: false,
		vote_average: 6.713,
		vote_count: 664,
	},
	{
		adult: false,
		backdrop_path: "/w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg",
		genre_ids: [16, 35, 14, 10402],
		id: 803796,
		original_language: "en",
		original_title: "KPop Demon Hunters",
		overview:
			"When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
		popularity: 159.4997,
		poster_path: "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
		release_date: "2025-06-20",
		title: "KPop Demon Hunters",
		video: false,
		vote_average: 8.3,
		vote_count: 1403,
	},
	{
		adult: false,
		backdrop_path: "/vHTFrcqJoCi1is3XN0PZe2LSnI2.jpg",
		genre_ids: [14, 10751, 28, 12],
		id: 1087192,
		original_language: "en",
		original_title: "How to Train Your Dragon",
		overview:
			"On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
		popularity: 156.8141,
		poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
		release_date: "2025-06-06",
		title: "How to Train Your Dragon",
		video: false,
		vote_average: 8.03,
		vote_count: 1908,
	},
	{
		adult: false,
		backdrop_path: "/uBB1aMga5ngZxsUQL5k36zeW3pB.jpg",
		genre_ids: [27, 10749],
		id: 1242011,
		original_language: "en",
		original_title: "Together",
		overview:
			"With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
		popularity: 133.7435,
		poster_path: "/m52XidzKx94bKlToZfEXUnL3pdy.jpg",
		release_date: "2025-07-28",
		title: "Together",
		video: false,
		vote_average: 7.129,
		vote_count: 422,
	},
	{
		adult: false,
		backdrop_path: "/2nwhxEyefcIFKwOrSigiamoIzu2.jpg",
		genre_ids: [28, 53, 18],
		id: 1119878,
		original_language: "en",
		original_title: "Ice Road: Vengeance",
		overview:
			"Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
		popularity: 130.1217,
		poster_path: "/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
		release_date: "2025-06-27",
		title: "Ice Road: Vengeance",
		video: false,
		vote_average: 6.474,
		vote_count: 370,
	},
	{
		adult: false,
		backdrop_path: "/jvpkBenB6hv19WWYVlaiow8zklq.jpg",
		genre_ids: [16, 10751, 35, 80, 12],
		id: 1175942,
		original_language: "en",
		original_title: "The Bad Guys 2",
		overview:
			"The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
		popularity: 120.9973,
		poster_path: "/26oSPnq0ct59l07QOXZKyzsiRtN.jpg",
		release_date: "2025-07-24",
		title: "The Bad Guys 2",
		video: false,
		vote_average: 7.789,
		vote_count: 369,
	},
	{
		adult: false,
		backdrop_path: "/i8QHgJKnsd8csNBo8fH9wYW2Y9E.jpg",
		genre_ids: [10749, 35],
		id: 1321439,
		original_language: "en",
		original_title: "The Wrong Paris",
		overview:
			"Dawn thinks she's joining a dating show in Paris, France, only to land in Paris, Texas. She has an exit plan — until sparks fly with the cowboy bachelor.",
		popularity: 120.4577,
		poster_path: "/A0KRoR842OgNByCfw9iFHbWoeR9.jpg",
		release_date: "2025-09-11",
		title: "The Wrong Paris",
		video: false,
		vote_average: 6.753,
		vote_count: 81,
	},
	{
		adult: false,
		backdrop_path: "/xSD0q1FiuZkvHuy7uscOLbmd1hR.jpg",
		genre_ids: [12, 28, 14],
		id: 13494,
		original_language: "en",
		original_title: "Red Sonja",
		overview:
			"A young girl rises from the ashes of tragedy to become the most feared warrior woman of all time: the She-Devil with a Sword.",
		popularity: 106.9063,
		poster_path: "/l10eghFN1nQmWwMSt91MlLvZZFA.jpg",
		release_date: "2025-07-31",
		title: "Red Sonja",
		video: false,
		vote_average: 5.651,
		vote_count: 86,
	},
	{
		adult: false,
		backdrop_path: "/8jeDyvFQKgss36FbGAmGQVzPXlH.jpg",
		genre_ids: [53, 28, 35],
		id: 1151334,
		original_language: "en",
		original_title: "Eenie Meanie",
		overview:
			"A former teenage getaway driver gets dragged back into her unsavory past when a former employer offers her a chance to save the life of her chronically unreliable ex-boyfriend.",
		popularity: 106.1715,
		poster_path: "/12Va3oO3oYUdOd75zM57Nx1976a.jpg",
		release_date: "2025-08-21",
		title: "Eenie Meanie",
		video: false,
		vote_average: 6.4,
		vote_count: 189,
	},
	{
		adult: false,
		backdrop_path: "/yth78N88nwokepnOe5atwPGfTL1.jpg",
		genre_ids: [28, 80, 53],
		id: 1382406,
		original_language: "zh",
		original_title: "惊天大营救",
		overview:
			"A veteran Muay Thai expert goes on a take-no-prisoners mission of revenge after his wife and daughter are brutally murdered by mysterious forces.",
		popularity: 98.5179,
		poster_path: "/nML8rOI4GOiiEsXgknuhZeUF8M7.jpg",
		release_date: "2024-12-05",
		title: "Striking Rescue",
		video: false,
		vote_average: 7.556,
		vote_count: 116,
	},
	{
		adult: false,
		backdrop_path: "/94KROr9xO9u5Tq5gTdCJlVRRfhm.jpg",
		genre_ids: [53, 80, 18],
		id: 1242434,
		original_language: "en",
		original_title: "Highest 2 Lowest",
		overview:
			'When a titan music mogul, widely known as having the "best ears in the business", is targeted with a ransom plot, he is jammed up in a life-or-death moral dilemma.',
		popularity: 90.4211,
		poster_path: "/kOzwIr0R7WhaFgoYUZFLPZA2RBZ.jpg",
		release_date: "2025-08-14",
		title: "Highest 2 Lowest",
		video: false,
		vote_average: 5.8,
		vote_count: 220,
	},
	{
		adult: false,
		backdrop_path: "/7U6sslMcPXPs9MIH5IvAl8ttTth.jpg",
		genre_ids: [53, 878, 27],
		id: 1530127,
		original_language: "en",
		original_title: "Lookout",
		overview:
			"Seeking peace away from her turbulent life, a young woman accepts a job as a fire lookout at a remote wilderness tower. As she settles into her new role, eerie disturbances and strange occurrences begin to unfold, and she must uncover the chilling secrets that disrupt her isolation before it’s too late.",
		popularity: 84.4383,
		poster_path: "/nlMsTk94ylLywUdDWsOqwBDi19l.jpg",
		release_date: "2025-09-02",
		title: "Lookout",
		video: false,
		vote_average: 6.4,
		vote_count: 5,
	},
	{
		adult: false,
		backdrop_path: "/sItIskd5xpiE64bBWYwZintkGf3.jpg",
		genre_ids: [28, 53, 80],
		id: 541671,
		original_language: "en",
		original_title: "Ballerina",
		overview:
			"Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
		popularity: 95.4109,
		poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
		release_date: "2025-06-04",
		title: "Ballerina",
		video: false,
		vote_average: 7.376,
		vote_count: 1642,
	},
	{
		adult: false,
		backdrop_path: "/fMlAg1CyHTsCktwQrp74rl9RMwJ.jpg",
		genre_ids: [27, 53],
		id: 138843,
		original_language: "en",
		original_title: "The Conjuring",
		overview:
			"Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. Forced to confront a powerful entity, the Warrens find themselves caught in the most terrifying case of their lives.",
		popularity: 88.4779,
		poster_path: "/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
		release_date: "2013-07-18",
		title: "The Conjuring",
		video: false,
		vote_average: 7.5,
		vote_count: 12157,
	},
	{
		adult: false,
		backdrop_path: "/28zX1DO1NJWeS1e573lSJQ9kiVh.jpg",
		genre_ids: [53, 27],
		id: 604079,
		original_language: "en",
		original_title: "The Long Walk",
		overview:
			"In a dystopian, alternate-America ruled by a totalitarian regime, 50 teenage boys take part in a deadly annual walking contest, forced to maintain a minimum pace or be executed, until only one survivor remains.",
		popularity: 87.3677,
		poster_path: "/wobVTa99eW0ht6c1rNNzLkazPtR.jpg",
		release_date: "2025-09-10",
		title: "The Long Walk",
		video: false,
		vote_average: 7.288,
		vote_count: 80,
	},
	{
		adult: false,
		backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
		genre_ids: [35, 14, 10751],
		id: 1125257,
		original_language: "en",
		original_title: "Freakier Friday",
		overview:
			"Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
		popularity: 76.6737,
		poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
		release_date: "2025-08-06",
		title: "Freakier Friday",
		video: false,
		vote_average: 6.896,
		vote_count: 168,
	},
];
